/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CertificateRouteImport } from './routes/certificate'
import { Route as ApiCertificatesCreateRouteImport } from './routes/api/certificates/create'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CertificateRoute = CertificateRouteImport.update({
  id: '/certificate',
  path: '/certificate',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCertificatesCreateRoute = ApiCertificatesCreateRouteImport.update({
  id: '/api/certificates/create',
  path: '/api/certificates/create',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/certificate': typeof CertificateRoute
  '/api/certificates/create': typeof ApiCertificatesCreateRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/certificate': typeof CertificateRoute
  '/api/certificates/create': typeof ApiCertificatesCreateRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/certificate': typeof CertificateRoute
  '/api/certificates/create': typeof ApiCertificatesCreateRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/certificate' | '/api/certificates/create'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/certificate' | '/api/certificates/create'
  id: '__root__' | '/' | '/certificate' | '/api/certificates/create'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CertificateRoute: typeof CertificateRoute
  ApiCertificatesCreateRoute: typeof ApiCertificatesCreateRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/certificate': {
      id: '/certificate'
      path: '/certificate'
      fullPath: '/certificate'
      preLoaderRoute: typeof CertificateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/certificates/create': {
      id: '/api/certificates/create'
      path: '/api/certificates/create'
      fullPath: '/api/certificates/create'
      preLoaderRoute: typeof ApiCertificatesCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CertificateRoute: CertificateRoute,
  ApiCertificatesCreateRoute: ApiCertificatesCreateRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
